name: Terraform Apply
on:
  push:
    branches:
      - main # Replace with your branch name

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: v1.4.4 # Replace with your desired Terraform version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired region

      - name: Terraform Init
        run: terraform init
        working-directory: ./task7 # Specify your desired working directory

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./task7 # Specify your desired working directory

